### ISSUE TITLE
Expose configurable --simpla-primary-color prop

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-styles#1]
If all Simpla elements define their colors like so:

```
:host {
  color: var(--simpla-primary-color, --simpla-blue);
}
```

Rather than just `var(--simpla-blue)`, then users can change the primary color, and hence instantly theme, the whole ecosystem by just setting 

```
html {
  --simpla-primary-color: red
}
```

In their document. Could be really good, give some personalisation control to the developers, to match a brand and become really seamless. Obviously we can't absolutely enforce this, but it can be a guideline that we uphold in any kind of public registry.

**Comment by madeleineostoja** [comment]
Definitely doing this, though the default `--simpla-primary-color` should be defined here, to make it easier for element authors.

In `simpla-styles`

```css
:root {
  --simpla-primary-color: var(--simpla-blue);
}
```

In element

```css
:host {
  color: var(--simpla-primary-color);
}
```

In userland

```css
html {
  --simpla-primary-color: red
}
```

That should work according to the spec, but depends on how the new shady CSS shim behaves when its global.
